### ISSUE TITLE
Suggestions for "log" don't show up before it's imported

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-go#1186]
I tried several unimported packages, and autocomplete works for them, but it doesn't work just for `log` for some reason.

e.g. `fmt.` -> Shows `Errorf`, `Printf`, etc.

`log.` -> nothing...

Once I import `log`, its suggestions show up.

**Comment by ramya-rao-a** [comment]
<img width="474" alt="screen shot 2017-09-04 at 10 37 39 pm" src="https://user-images.githubusercontent.com/16890566/30046942-2d912650-91c3-11e7-8efb-35bda50f1441.png">

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/30067363-6f0cbaa8-920f-11e7-8bdc-0157c43a8ae5.png)

**Comment by sgyang** [comment]
So do I. (code 1.15.1, vscode-go 0.6.64)
It may be related to #1152. I set "go.autocompleteUnimportedPackages" to true but it didn't work.
![go_fmt](https://user-images.githubusercontent.com/1253518/30093220-81311c5a-92f6-11e7-8e5d-a913c1842df5.png)
![go_log](https://user-images.githubusercontent.com/1253518/30093228-87109826-92f6-11e7-9dfb-415b29fe3334.png)

**Comment by sgyang** [comment]
OK I found version 0.6.62 worked properly. 0.6.63 and 0.6.64 didn't work.

FYI: I did:

- Remove current vscode-go
- Disable auto-update feature of extensions (`"extensions.autoUpdate": false`) 
- Download previous version from https://lukehoban.gallery.vsassets.io/_apis/public/gallery/publisher/lukehoban/extension/go/0.6.62/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
- Rename it to go-0.6.62.vsix
- Install this by `code --install-extension go-0.6.62.vsix`

And then the issue is fixed.

**Comment by ramya-rao-a** [comment]
@sgyang Do you also the issue only for the `log` pkg? And `fmt` works?

**Comment by sgyang** [comment]
@ramya-rao-a The issue is related to all unimported packages. This `log` and `fmt` thing is just an example.
Before importing `log`, hitting `log` does not show suggestions, but after importing `log`, hitting `log` fires auto-completion. Previously, auto-completion works properly without importing packages (and I love this feature).
And it is not only about these built-in packages. For example, hitting `grpclog` doesn't show any suggestions although grpc-go (https://github.com/grpc/grpc-go/) is installed and the `grpclog` is an unique identifier. 0.6.62 fixes this.

**Comment by ramya-rao-a** [comment]
@sgyang The reason I asked about log vs fmt was because that is what @roblourens originally reported in this issue. That when testing completion for unimported packages, things worked for fmt but not for log.

Can you follow the instructions on https://github.com/Microsoft/vscode-go/issues/1152#issuecomment-324838203 and share your results in that issue?

**Comment by Slacki** [comment]
I am still having this issue. vscode-go 0.6.66, and VS Code Version 1.17.2 linux.

**Comment by ramya-rao-a** [comment]
@Slacki  You are not seeing completions from std library or custom packages or both?

**Comment by Slacki** [comment]
Standard library. Exactly the same problem as in this comment https://github.com/Microsoft/vscode-go/issues/1186#issuecomment-327364956.

**Comment by ramya-rao-a** [comment]
I don't see why the suggestions wouldn't show up for `log`, but will show up for `fmt`. 

I can help you set up a local environment for the Go extension and help you debug the issue if you are up for it.

- Follow the instructions for [Building and Debugging the extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- Put a breakpoint in the file `goSuggest.ts` at https://github.com/Microsoft/vscode-go/blob/0.6.66/src/goSuggest.ts#L91
- If you have already pressed F5 and the extension host instance is up, reload. Else Press F5 and when the extension host instance is up, open any folder with Go code and try to repro

`gocode` gives completion for standard library pkgs even if they are not imported.
When the above breakpoint is hit, you should have suggestions. If you don't and you see this issue only for standard library pkg, then I would say the issue is with `gocode`.

You can try updating `gocode` as well
- Run `gocode close`
- Run `Go: Install/Update Tools` (it will update all tools) or update `gocode` separately

**Comment by faceair** [comment]
I'm having the same issue. And after run `Go: Install/Update Tools`, everything is ok. 👍

**Comment by ramya-rao-a** [comment]
Am closing this issue as there is nothing concrete for me to go on with.
If anyone has problems with the completions, please log a new issue and we can take it from there.
