### ISSUE TITLE
Auto-complete fails in snippet completion

### ISSUE THREAD

**Issue by tj** [microsoft/vscode-go#2474]
I'm not sure if this is a VScode-level problem or something specific to Go / the language server but I think this used to work.

<img width="383" alt="Screen Shot 2019-04-25 at 2 47 28 PM" src="https://user-images.githubusercontent.com/25254/56740561-1733ab80-6769-11e9-8d9b-1476d81fefa4.png">
<img width="404" alt="Screen Shot 2019-04-25 at 2 47 37 PM" src="https://user-images.githubusercontent.com/25254/56740562-1733ab80-6769-11e9-99b5-a35df09971aa.png">

**Comment by Hawken94** [comment]
#2469

**Comment by tj** [comment]
I think this is different, this only happens during a snippet's execution

**Comment by tj** [comment]
Looks like it's not just snippets (manually typed defer in this case):

<img width="589" alt="Screen Shot 2019-04-27 at 2 50 18 PM" src="https://user-images.githubusercontent.com/25254/56850530-d324e000-68fb-11e9-875f-ccc113c282be.png">
<img width="495" alt="Screen Shot 2019-04-27 at 2 50 23 PM" src="https://user-images.githubusercontent.com/25254/56850531-d324e000-68fb-11e9-8114-1cd936d94e57.png">

**Comment by imkos** [comment]
0.9.2 is normal, 0.10.x has problems, and now auto-complete input lowercase will not match first.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @tj and @imkos 

Can you share any Go related settings that you may have added/edited?

Also, please try the [latest beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension which has the fix for #2469 and let me know how it makes any difference here.

**Comment by imkos** [comment]
I tried this version (0.10.2-beta.1) and it seems that the recovery is as good as the 0.9.2 version.

**Comment by tj** [comment]
@ramya-rao-a looks like it's still happening in the latest beta

**Comment by tj** [comment]
Reverting back to the latest non-beta fixes the `tabSize`

**Comment by ramya-rao-a** [comment]
@tj The tab size should be back to normal in the [beta update](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension)(0.10.2-beta.2) that I just released

Your settings look fine. 

Can you share a small code sample where I can try and replicate your issue?

**Comment by tj** [comment]
Sure! It may be a `gopls` issue, but if you have:

```go
package main

import (
	"flag"
)

func main() {
	flag.Parse()
}
```

typing `flag.P` will show `Parse`, but typing `defer flag.P` gives me:

<img width="572" alt="Screen Shot 2019-04-30 at 5 27 26 PM" src="https://user-images.githubusercontent.com/25254/56977528-41240e00-6b6d-11e9-9ae1-cc3dc558bf66.png">

I had the same results when using auto-complete in snippets but it looks like the same issue

**Comment by ramya-rao-a** [comment]
@tj On second thoughts your issue is definitely different from #2469 
#2469 is about the unimproved packages showing up in completions when they shouldn't
And your issue is about getting different completions for the same input but different locations

Please go to `View` -> `Output`. In the dropdown that appears on the top right corner of the panel, do you see `gopls` or `go-langserver`?

**Comment by tj** [comment]
Looks like I have `gopls` there

**Comment by stamblerre** [comment]
The defer issue is https://github.com/golang/go/issues/29313. `gopls` autocompletion is still not perfect, and there are occasional cases where autocompletion does not work as expected. Please file any cases that you see [here](https://github.com/golang/go/issues).

**Comment by tj** [comment]
hmm ok interesting about `defer`. I see the same behaviour with snippets though, for example typing `for range flag.P` is correct in showing `Parse` in my case, but if I have a `for range $1` snippet and start to type `flag.P` it shows all that other built-in stuff.

**Comment by stamblerre** [comment]
I think this is still a `gopls` issue with the range statement - particularly because looking at your original screenshot, it looks the like the range statement has an error (`for _, := `). `gopls` occasionally will fail on broken code.

**Comment by tj** [comment]
@stamblerre ahh that makes sense, my snippet goes to the right-hand side first and then left, but you're right, for that moment it's not valid Go, that makes sense now

**Comment by tj** [comment]
That did the trick! Closing this one, sorry for the noise!

**Comment by stamblerre** [comment]
Not noise at all! Filed https://github.com/golang/go/issues/31907 so that we can ultimately handle more broken cases. Thank you!
