### ISSUE TITLE
Goto Definition, Hover, Signature Help does not work for `net` package

### ISSUE THREAD

**Issue by Aukstkalnis** [Microsoft/vscode-go#442]
Windows 7 x86
VSCode 1.4.0
Go 0.6.43

When mouse is crossed on function than I should see function preview like this:

![image](https://cloud.githubusercontent.com/assets/9738294/17800793/bc339c6e-65ee-11e6-8df7-13b710ecc843.png)

However, when I do this to net library functions I do see Loading.. for a blink of an eye and no preview is shown.

Also, ATL+F12 does not work on this library.

**Comment by lukehoban** [comment]
Could you provide a more complete example of the problem?

**Comment by Aukstkalnis** [comment]
Example Program:
package main

import "net"

func main() {
	net.Listen("tcp","192.168.8.119:7000");
}

And when I write net.Listen(
I should see parameters that I should see like:
![image](https://cloud.githubusercontent.com/assets/9738294/17844378/6b9d6bcc-6841-11e6-8c8a-30025f0458c9.png)
But with net library there is no list and when I cross with mouse on Listen word I see loading and it disappears in less then a second and I can not see definition of that function.

**Comment by fastest963** [comment]
VSCode 1.6.1
Go 0.6.47

I'm having the same issue. It shows "Loading..." when hovering over `net` functions and won't let me `Go To Definition` on `net` functions. I turned on the developer console and don't see any errors or related messages in there.

**Comment by ramya-rao-a** [comment]
This is an issue with `godef` itself. 

https://github.com/rogpeppe/godef/issues/48

https://github.com/Microsoft/vscode-go/issues/599

**Comment by leaxoy** [comment]
May be we can use gogetdoc instead both godef and godoc.
Use gogetdoc `-json` option we have five properties of `name`, `import`, `decl`, `doc`, `pos`.
For example:
```{"name":"Now","import":"time","decl":"func Now() Time","doc":"Now returns the current local time.\n","pos":"/usr/local/opt/go/libexec/src/time/time.go:777:6"}```
Which give us position for godef's work, and `doc` and `decl` for godoc's work

**Comment by leaxoy** [comment]
```
export function definitionLocation(document: vscode.TextDocument, position: vscode.Position, includeDocs = true): Promise<GoDefinitionInformtation> {
	return new Promise<GoDefinitionInformtation>((resolve, reject) => {
		let wordAtPosition = document.getWordRangeAtPosition(position);
		let offset = byteOffsetAt(document, position);
		let gogetdoc = getBinPath('gogetdoc');
		let p = cp.execFile(gogetdoc, ['-json', '-pos=' + document.fileName + ':#' + offset.toString()], {}, (err, stdout, stderr) => {
			try {
				if (err && (<any>err).code === 'ENOENT') {
					promptForMissingTool('gogetdoc');
				}
				if (err) return resolve(null);
				let goDocInfomation: GoDocInfomation = JSON.parse(stdout.toString());
				if (goDocInfomation.doc === 'A concurrent prime sieve\n') {
					return resolve({
						file: null,
						line: 0,
						column: 0,
						signature: ['builtin keyword'],
						doc: goDocInfomation.doc
					});
				}
				let match = /(.*):(\d+):(\d+)/.exec(goDocInfomation.pos);
				if (!match) {
					return resolve({
						file: null,
						line: 0,
						column: 0,
						signature: goDocInfomation.decl.split('\n'),
						doc: goDocInfomation.doc
					});
				}
				let [_, file, line, col] = match;
				return resolve({
					file: file,
					line: +line - 1,
					column: +col - 1,
					signature: goDocInfomation.decl.split('\n'),
					doc: goDocInfomation.doc
				});
			} catch (e) {
				reject(e);
			}
		});
		p.stdin.end(document.getText());
	});
}
```

**Comment by ramya-rao-a** [comment]
In the latest update of the Go extension (0.6.50), we now support the use of `gogetdoc` for **Goto/Peek Definition, Hover info and Signature Help** features. Add `"go.docsTool": "gogetdoc"` to your setting to enable the use of `gogetdoc` and that should fix this issue.

**Comment by zgiber** [comment]
@ramya-rao-a Thank you for the fix, however simply performing the steps described in the comment does not solve the problem in my case. It makes all the Goto/Peek Definition, Hover info and Signature Help functions stop working. Perhaps there is something I've missed? Go Extension 0.6.50, VSCode Version 1.7.2 (1.7.2).

**Comment by ramya-rao-a** [comment]
@zgiber What version of Go are you using? Can you share the output of `go version` ?
If you are using Go from source, then yes in Go extension 0.6.50, Goto/Peek Definition, Hover info and Signature Help features stopped working. The newest update 0.6.51 has the fix for it

**Comment by zgiber** [comment]
@ramya-rao-a I'm using go version go1.7.4 darwin/amd64, not from source, but from archive. The Go plugin is now version 0.6.51. After adding the line: `"go.docsTool": "gogetdoc",` to user settings and restarting VSCode, Goto/Peek definition, Hover info, Signature stopped working. Removing the line restored the usual functionalities, but then the original issue (no tooltip on net package's functions) remains.

**Comment by ramya-rao-a** [comment]
@zgiber Since what you are seeing is specific to `gogetdoc`, I opened a new issue to track it #679. Lets continue the discussion in that thread
